### ISSUE TITLE
Weird rendering on Safari

### ISSUE THREAD

**Issue by Arvinje** [rastikerdar/mirza-font#1]
I'm currently facing the problem only on Safari, whereas it seems to be working fine on Chrome.
![screen shot 1394-07-23 at 10 23 42 am](https://cloud.githubusercontent.com/assets/3445247/10506711/84d1316a-7327-11e5-8b67-a74a5d6b9af9.png)
Not sure if it's a problem with the font itself or not.

**Comment by rastikerdar** [comment]
فکر می کنم مشکل از نوعی خروجی است که برنامه فونت فورج تولید می کند. علیرغم انتخاب گزینه اپل در هنگام تولید خروجی، باز هم این مشکل پابرجاست. اینطور که تحقیق کردم متوجه شدم نوع نمایش در مک به صورت اوپن تایپ نمی باشد و باید فونت به حالت مناسب آن تبدیل گردد یعنی:
ATT

از آنجایی که اطلاعاتی در این زمینه ندارم و به دوستان دست اندرکار فونت های فارسی یا عربی نیز برای کمک گرفتن دسترسی ندارم و همچنین هیچ گونه دستگاه اپلی در دست و بالم نیست کار برایم پیچیده شده.

**Comment by rastikerdar** [comment]
ممنون میشم دوباره صفحه فونت را ملاحظه بفرمایید ببینید مشکل رفع شده یا خیر؟

**Comment by Arvinje** [comment]
@rastikerdar 
![screen shot 1394-07-23 at 7 15 28 pm](https://cloud.githubusercontent.com/assets/3445247/10519125/5145e2c4-7371-11e5-80c1-237b1639e884.png)
تیتر‌ها مثل اینکه درست شدن

**Comment by rastikerdar** [comment]
دوباره لطفا :D

**Comment by Arvinje** [comment]
کامل حل شده
:+1: 
![screen shot 1394-07-23 at 8 05 07 pm](https://cloud.githubusercontent.com/assets/3445247/10520667/3dc0a5b6-7378-11e5-83d1-76db9b59aa04.png)
