### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by sasy360** [rastikerdar/mirza-font#3]
Hi there,
This font claims to be under SIL open font license but source code is nowhere to be found. (ttf and woffs are binary formats. By source code I mean either FontForge's native sfd or UFO)
Is this by design?

**Comment by rastikerdar** [comment]
فایل فونت فورج اضافه شد.
با تشکر از اینکه گزارش فرمودید

**Comment by sasy360** [comment]
Awesome!
Closing the issue.
